### PR TITLE
updated typos on the index.html file

### PR DESCRIPTION
**Pull request by HaleyOgbuanya**

### CODE REVIEW

**Comment by Isabellekosy0** [comment]
We all love u

**Comment by Isabellekosy0** [comment]
💋

**Comment by HaleyOgbuanya** [comment]
https://haleyogbuanya.github.io/Dice.game/

**Comment by HaleyOgbuanya** [comment]
https://haleyogbuanya.github.io/Dice.game/

https://haleyogbuanya.github.io/Dice.game/

https://haleyogbuanya.github.io/Dice.game/


https://haleyogbuanya.github.io/Dice.game/


https://haleyogbuanya.github.io/Dice.game/

**Comment by Isabellekosy0** [comment]
**https://iosvaldo.github.io/tindog/images/iphone12.pnghttps://iosvaldo.github.io/tindog/images/iphone12.pnghttps://iosvaldo.github.io/tindog/images/iphone12.pnghttps://iosvaldo.github.io/tindog/images/iphone12.pngbhttps://iosvaldo.github.io/tindog/images/iphone12.pnghttps://iosvaldo.github.io/tindog/images/iphone12.pngvvvhttps://iosvaldo.github.io/tindog/images/iphone12.pngvhttps://iosvaldo.github.io/tindog/images/iphone12.png_****

**Comment by HaleyOgbuanya** [comment]
IT DOSEN'T WORK😑😑😶

**Comment by Isabellekosy0** [comment]
ok...

**Comment by HaleyOgbuanya** [comment]
Will do!

**Pull request merged**
